// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0
// 	protoc        v3.12.3
// source: migration/migration.proto

package migration

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Migration_Algorithm int32

const (
	Migration_ALGO_UNSPECIFIED Migration_Algorithm = 0
	Migration_ALGO_SHA1        Migration_Algorithm = 1
	Migration_ALGO_SHA256      Migration_Algorithm = 2 // WARNING: Google Authenticator not supported SHA256.
	Migration_ALGO_SHA512      Migration_Algorithm = 3 // WARNING: Google Authenticator not supported SHA512.
)

// Enum value maps for Migration_Algorithm.
var (
	Migration_Algorithm_name = map[int32]string{
		0: "ALGO_UNSPECIFIED",
		1: "ALGO_SHA1",
		2: "ALGO_SHA256",
		3: "ALGO_SHA512",
	}
	Migration_Algorithm_value = map[string]int32{
		"ALGO_UNSPECIFIED": 0,
		"ALGO_SHA1":        1,
		"ALGO_SHA256":      2,
		"ALGO_SHA512":      3,
	}
)

func (x Migration_Algorithm) Enum() *Migration_Algorithm {
	p := new(Migration_Algorithm)
	*p = x
	return p
}

func (x Migration_Algorithm) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Migration_Algorithm) Descriptor() protoreflect.EnumDescriptor {
	return file_migration_migration_proto_enumTypes[0].Descriptor()
}

func (Migration_Algorithm) Type() protoreflect.EnumType {
	return &file_migration_migration_proto_enumTypes[0]
}

func (x Migration_Algorithm) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Migration_Algorithm.Descriptor instead.
func (Migration_Algorithm) EnumDescriptor() ([]byte, []int) {
	return file_migration_migration_proto_rawDescGZIP(), []int{0, 0}
}

type Migration_OtpType int32

const (
	Migration_OTP_INVALID Migration_OtpType = 0
	Migration_OTP_HOTP    Migration_OtpType = 1
	Migration_OTP_TOTP    Migration_OtpType = 2
)

// Enum value maps for Migration_OtpType.
var (
	Migration_OtpType_name = map[int32]string{
		0: "OTP_INVALID",
		1: "OTP_HOTP",
		2: "OTP_TOTP",
	}
	Migration_OtpType_value = map[string]int32{
		"OTP_INVALID": 0,
		"OTP_HOTP":    1,
		"OTP_TOTP":    2,
	}
)

func (x Migration_OtpType) Enum() *Migration_OtpType {
	p := new(Migration_OtpType)
	*p = x
	return p
}

func (x Migration_OtpType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Migration_OtpType) Descriptor() protoreflect.EnumDescriptor {
	return file_migration_migration_proto_enumTypes[1].Descriptor()
}

func (Migration_OtpType) Type() protoreflect.EnumType {
	return &file_migration_migration_proto_enumTypes[1]
}

func (x Migration_OtpType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Migration_OtpType.Descriptor instead.
func (Migration_OtpType) EnumDescriptor() ([]byte, []int) {
	return file_migration_migration_proto_rawDescGZIP(), []int{0, 1}
}

type Migration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OtpParameters []*Migration_OtpParameter `protobuf:"bytes,1,rep,name=otp_parameters,json=otpParameters,proto3" json:"otp_parameters,omitempty"`
	Version       int32                     `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	BatchSize     int32                     `protobuf:"varint,3,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`
	BatchIndex    int32                     `protobuf:"varint,4,opt,name=batch_index,json=batchIndex,proto3" json:"batch_index,omitempty"`
	BatchId       int32                     `protobuf:"varint,5,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
}

func (x *Migration) Reset() {
	*x = Migration{}
	if protoimpl.UnsafeEnabled {
		mi := &file_migration_migration_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Migration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Migration) ProtoMessage() {}

func (x *Migration) ProtoReflect() protoreflect.Message {
	mi := &file_migration_migration_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Migration.ProtoReflect.Descriptor instead.
func (*Migration) Descriptor() ([]byte, []int) {
	return file_migration_migration_proto_rawDescGZIP(), []int{0}
}

func (x *Migration) GetOtpParameters() []*Migration_OtpParameter {
	if x != nil {
		return x.OtpParameters
	}
	return nil
}

func (x *Migration) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Migration) GetBatchSize() int32 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

func (x *Migration) GetBatchIndex() int32 {
	if x != nil {
		return x.BatchIndex
	}
	return 0
}

func (x *Migration) GetBatchId() int32 {
	if x != nil {
		return x.BatchId
	}
	return 0
}

type Migration_OtpParameter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Secret    []byte              `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	Name      string              `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Issuer    string              `protobuf:"bytes,3,opt,name=issuer,proto3" json:"issuer,omitempty"`
	Algorithm Migration_Algorithm `protobuf:"varint,4,opt,name=algorithm,proto3,enum=Migration_Algorithm" json:"algorithm,omitempty"`
	Digits    int32               `protobuf:"varint,5,opt,name=digits,proto3" json:"digits,omitempty"`
	Type      Migration_OtpType   `protobuf:"varint,6,opt,name=type,proto3,enum=Migration_OtpType" json:"type,omitempty"`
	Counter   int64               `protobuf:"varint,7,opt,name=counter,proto3" json:"counter,omitempty"`
	Period    int64               `protobuf:"varint,8,opt,name=period,proto3" json:"period,omitempty"` // REVIEW: "Google Authenticator" for Android: not supported `period`, for iOS: not supported otpauth migration.
}

func (x *Migration_OtpParameter) Reset() {
	*x = Migration_OtpParameter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_migration_migration_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Migration_OtpParameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Migration_OtpParameter) ProtoMessage() {}

func (x *Migration_OtpParameter) ProtoReflect() protoreflect.Message {
	mi := &file_migration_migration_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Migration_OtpParameter.ProtoReflect.Descriptor instead.
func (*Migration_OtpParameter) Descriptor() ([]byte, []int) {
	return file_migration_migration_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Migration_OtpParameter) GetSecret() []byte {
	if x != nil {
		return x.Secret
	}
	return nil
}

func (x *Migration_OtpParameter) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Migration_OtpParameter) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *Migration_OtpParameter) GetAlgorithm() Migration_Algorithm {
	if x != nil {
		return x.Algorithm
	}
	return Migration_ALGO_UNSPECIFIED
}

func (x *Migration_OtpParameter) GetDigits() int32 {
	if x != nil {
		return x.Digits
	}
	return 0
}

func (x *Migration_OtpParameter) GetType() Migration_OtpType {
	if x != nil {
		return x.Type
	}
	return Migration_OTP_INVALID
}

func (x *Migration_OtpParameter) GetCounter() int64 {
	if x != nil {
		return x.Counter
	}
	return 0
}

func (x *Migration_OtpParameter) GetPeriod() int64 {
	if x != nil {
		return x.Period
	}
	return 0
}

var File_migration_migration_proto protoreflect.FileDescriptor

var file_migration_migration_proto_rawDesc = []byte{
	0x0a, 0x19, 0x6d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x6d, 0x69, 0x67, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc7, 0x04, 0x0a, 0x09,
	0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3e, 0x0a, 0x0e, 0x6f, 0x74, 0x70,
	0x5f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x17, 0x2e, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4f, 0x74,
	0x70, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x52, 0x0d, 0x6f, 0x74, 0x70, 0x50,
	0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x73, 0x69, 0x7a,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x62, 0x61, 0x74, 0x63, 0x68, 0x53, 0x69,
	0x7a, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x62, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x69, 0x6e, 0x64, 0x65,
	0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x62, 0x61, 0x74, 0x63, 0x68, 0x49, 0x6e,
	0x64, 0x65, 0x78, 0x12, 0x19, 0x0a, 0x08, 0x62, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x69, 0x64, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x62, 0x61, 0x74, 0x63, 0x68, 0x49, 0x64, 0x1a, 0xf8,
	0x01, 0x0a, 0x0c, 0x4f, 0x74, 0x70, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x06, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x69,
	0x73, 0x73, 0x75, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69, 0x73, 0x73,
	0x75, 0x65, 0x72, 0x12, 0x32, 0x0a, 0x09, 0x61, 0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74, 0x68, 0x6d,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x41, 0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74, 0x68, 0x6d, 0x52, 0x09, 0x61, 0x6c,
	0x67, 0x6f, 0x72, 0x69, 0x74, 0x68, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x69, 0x67, 0x69, 0x74,
	0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x64, 0x69, 0x67, 0x69, 0x74, 0x73, 0x12,
	0x26, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e,
	0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4f, 0x74, 0x70, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x65, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65,
	0x72, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x22, 0x52, 0x0a, 0x09, 0x41, 0x6c, 0x67,
	0x6f, 0x72, 0x69, 0x74, 0x68, 0x6d, 0x12, 0x14, 0x0a, 0x10, 0x41, 0x4c, 0x47, 0x4f, 0x5f, 0x55,
	0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09,
	0x41, 0x4c, 0x47, 0x4f, 0x5f, 0x53, 0x48, 0x41, 0x31, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x41,
	0x4c, 0x47, 0x4f, 0x5f, 0x53, 0x48, 0x41, 0x32, 0x35, 0x36, 0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b,
	0x41, 0x4c, 0x47, 0x4f, 0x5f, 0x53, 0x48, 0x41, 0x35, 0x31, 0x32, 0x10, 0x03, 0x22, 0x36, 0x0a,
	0x07, 0x4f, 0x74, 0x70, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x4f, 0x54, 0x50, 0x5f,
	0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x4f, 0x54, 0x50,
	0x5f, 0x48, 0x4f, 0x54, 0x50, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x4f, 0x54, 0x50, 0x5f, 0x54,
	0x4f, 0x54, 0x50, 0x10, 0x02, 0x42, 0x26, 0x5a, 0x24, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x50, 0x68, 0x65, 0x72, 0x6f, 0x78, 0x2f, 0x6f, 0x74, 0x70, 0x61,
	0x75, 0x74, 0x68, 0x2f, 0x6d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_migration_migration_proto_rawDescOnce sync.Once
	file_migration_migration_proto_rawDescData = file_migration_migration_proto_rawDesc
)

func file_migration_migration_proto_rawDescGZIP() []byte {
	file_migration_migration_proto_rawDescOnce.Do(func() {
		file_migration_migration_proto_rawDescData = protoimpl.X.CompressGZIP(file_migration_migration_proto_rawDescData)
	})
	return file_migration_migration_proto_rawDescData
}

var file_migration_migration_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_migration_migration_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_migration_migration_proto_goTypes = []interface{}{
	(Migration_Algorithm)(0),       // 0: Migration.Algorithm
	(Migration_OtpType)(0),         // 1: Migration.OtpType
	(*Migration)(nil),              // 2: Migration
	(*Migration_OtpParameter)(nil), // 3: Migration.OtpParameter
}
var file_migration_migration_proto_depIdxs = []int32{
	3, // 0: Migration.otp_parameters:type_name -> Migration.OtpParameter
	0, // 1: Migration.OtpParameter.algorithm:type_name -> Migration.Algorithm
	1, // 2: Migration.OtpParameter.type:type_name -> Migration.OtpType
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_migration_migration_proto_init() }
func file_migration_migration_proto_init() {
	if File_migration_migration_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_migration_migration_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Migration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_migration_migration_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Migration_OtpParameter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_migration_migration_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_migration_migration_proto_goTypes,
		DependencyIndexes: file_migration_migration_proto_depIdxs,
		EnumInfos:         file_migration_migration_proto_enumTypes,
		MessageInfos:      file_migration_migration_proto_msgTypes,
	}.Build()
	File_migration_migration_proto = out.File
	file_migration_migration_proto_rawDesc = nil
	file_migration_migration_proto_goTypes = nil
	file_migration_migration_proto_depIdxs = nil
}
